user_service:
  source_dir: ./service
  container:
    name_prefix: linuxus_user_
    network_prefix: linuxus_user_net_
    base_ip: "10.10.1.0"
    runtime:
      uid: 1000
      gid: 1000
      user: user
      hostname: linuxus
      timezone: Asia/Seoul
    user:
      limits:
        cpu: 1.5
        memory: 512m
        pid: 128
        ulimits:
          nofile:
            soft: 1024
            hard: 2048
        disk: 512  # MB
        # network_bandwidth: 10mbit
        # session_timeout: 3600
    admin:
      user_id: alpha
      limits:
        cpu: 1.5
        memory: 512m
        pid: 128
        ulimits:
          nofile:
            soft: 1024
            hard: 2048
        disk: 512  # MB
        # network_bandwidth: 10mbit
        # session_timeout: 3600

auth_service:
  source_dir: ./auth
  container:
    name: linuxus_auth
    timezone: Asia/Seoul
    external_port: 8080
  url_path:
    login: login
    logout: logout
    service: service
    terminal: terminal
  auth_list_file:
    host_path: ./data/AUTH_LIST
    container_path: /data/AUTH_LIST
  security:
    session_secret: change-this-secret-before-production
    trusted_proxies: ""

manager_service:
  source_dir: ./manager
  container:
    name: linuxus_manager
    timezone: Asia/Seoul
    network: linuxus_manager_net
  session:
    timeout: 30s

volumes:
  host:
    volumes: ./volumes
    homes: ./volumes/homes
    share: ./volumes/share
    readonly: ./volumes/readonly
  container:
    share: /home/share
    readonly: /home/readonly
  disk_limit: 1024  # MB